# Change these first
owner: RenderbitTechnologies # Your GitHub organization or username, where this repository lives
repo: uptime-checker # The name of this repository

sites:
  - name: Renderbit
    url: https://www.renderbit.com/
  - name: Renderbit Staging
    url: https://new.renderbit.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there

  # baseUrl: /your-repo-name
  logoUrl: https://www.renderbit.com/images/logo.png
  name: Renderbit
  introTitle: "Your Partner in Scalable Innovation"
  introMessage: Our team combines startup agility with enterprise-grade engineering, helping you move faster, adapt smarter, and launch technology that continues to evolve with your business. When you work with us, you’re not just hiring developers, you’re gaining a partner invested in turning your vision into a resilient digital product.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/RenderbitTechnologies/renderbit-astro-site

